---
- name: Install NTP, mariadb, message queue, memcached & Etcd
  hosts: controller
  become: yes
  roles:
    - NTP
    - mariadb
    - message_queue
    - memcached

- name: Install OpenStack
  hosts: compute
  become: yes
  roles:
    - openstack





